# Generated by Django 5.2.14 on 2026-05-31 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='آدرس لینک (Slug)')),
                ('theme_color', models.CharField(choices=[('theme-mustard', 'خردلی/طلایی'), ('theme-orange', 'آجری/نارنجی'), ('theme-teal', 'سبزآبی'), ('theme-pink', 'صورتی'), ('theme-red', 'زرشکی/سنتی'), ('theme-indigo', 'نیلی/مدرن'), ('theme-purple', 'بنفش/گیمینگ'), ('theme-blue', 'آبی/موسیقی'), ('theme-brown', 'قهوه\u200cای/موکا')], default='theme-mustard', max_length=20, verbose_name='رنگ تم اسلایدر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان محصول')),
                ('code', models.CharField(max_length=50, verbose_name='کد محصول')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='عکس محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت اصلی (تومان)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='موجود/ناموجود')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created'],
            },
        ),
    ]
