# Generated by Django 5.2.14 on 2026-06-01 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سایز (مثلا ۱۲ متری)')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت این سایز (تومان)')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='موجودی این سایز')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.product', verbose_name='محصول')),
            ],
        ),
    ]
