# Generated by Django 5.2.14 on 2026-06-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfeature',
            name='show_in_top',
            field=models.BooleanField(default=False, verbose_name='نمایش در لیست کوتاه بالای صفحه'),
        ),
    ]
