# Generated by Django 5.2.14 on 2026-06-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='test', verbose_name='آدرس دقیق پستی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='test', max_length=50, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='test', max_length=50, verbose_name='نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='mobile',
            field=models.CharField(default='test', max_length=11, verbose_name='شماره موبایل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='national_code',
            field=models.CharField(default='test', max_length=10, verbose_name='کد ملی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='test', max_length=10, verbose_name='کد پستی'),
            preserve_default=False,
        ),
    ]
