# Generated by Django 5.2.14 on 2026-06-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_address_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='productsize',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف این سایز'),
        ),
    ]
