# Generated by Django 5.2.14 on 2026-06-16 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='theme_color',
        ),
    ]
