# Generated by Django 5.2.14 on 2026-06-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_category_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('post', 'پست پیشتاز'), ('tipax', 'تیپاکس')], default='post', max_length=20, verbose_name='روش ارسال'),
        ),
    ]
