# Generated by Django 5.2.14 on 2026-06-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/%Y/%m/', verbose_name='عکس بنر')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن کوچک بالای عنوان')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اصلی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('button_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن دکمه')),
                ('button_link', models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک دکمه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال؟')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'هیرو بنر',
                'verbose_name_plural': 'هیرو بنرها',
                'ordering': ['order', '-created'],
            },
        ),
    ]
