# Generated by Django 5.2.14 on 2026-06-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_heroslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('tipax', 'تیپاکس (پس\u200cکرایه)')], default='tipax', max_length=20, verbose_name='روش ارسال'),
        ),
    ]
