# Generated by Django 5.2.14 on 2026-06-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_shipping_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ترتیب نمایش (۱ بالاترین)'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_homepage',
            field=models.BooleanField(default=False, verbose_name='ساخت اسلایدر در صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_menu',
            field=models.BooleanField(default=False, verbose_name='نمایش در منوی بالای سایت'),
        ),
    ]
