# Generated by Django 5.2.14 on 2026-06-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
