# Generated by Django 5.2.14 on 2026-06-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_sales_count_product_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
